/**
 * @fileoverview Risk Assessment Pipeline Audit Schema (`risk_results` collection)
 * @module db/models/riskResult.model
 * @description
 * Sections 47-51 & `contracts/db/RiskResultsDocument.json`:
 * Persists the intermediate and final calculations generated by the multi-stage risk engine.
 *
 * Provable Safety Hierarchy:
 * Storing each stage's outputs independently provides mathematical auditability:
 * 1. Deterministic Baseline (Section 48): Raw meteorological score (0-100).
 * 2. Official Warning Floor (Section 49): Non-negotiable floor set by IMD/INCOIS cyclone bulletins.
 * 3. Hard Safety Rule Floors (Section 50): Hard bounds derived from vessel capabilities.
 * 4. Bounded LLM Nudge (Section 51): Constrained adjustment (+/-5 pts max) that CANNOT
 *    lower the score below the computed constraint floor.
 *
 * Section 48.4.1 LOCKED RULE: baseline_score = max(hourly_scores[].score) over
 * hours with computable data, null if none. max() (worst hour), not average -
 * an average would let one calm hour mask a dangerous one.
 */

const mongoose = require('mongoose');

const RiskResultSchema = new mongoose.Schema(
  {
    analysis_id: { type: String, required: true, unique: true, index: true },

    // Array of RiskAssessment objects, one per sampled point. Mixed because the
    // AI Service owns the shape (it is a locked contract, not ours to redefine)
    // and because hourly_scores/risk_factors are themselves nested structures.
    results: { type: [mongoose.Schema.Types.Mixed], default: [] },
  },
  {
    timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' },
    collection: 'risk_results',
    strict: false,
  }
);

module.exports = mongoose.model('RiskResult', RiskResultSchema);
