// src/modules/report/report.service.js
// ---------------------------------------------------------------------------
// Section 103: GET /api/v1/report/:analysis_id - generate/fetch a shareable
// advisory.
//
// CACHING IS A CORRECTNESS REQUIREMENT, NOT AN OPTIMISATION:
// A report is a RECORD. If a fisherman shares an advisory with their crew and
// the text changes when someone else opens it, the advisory is not trustworthy
// evidence. So a report is generated once per (analysis_id, language, format)
// and returned identically thereafter.
// ---------------------------------------------------------------------------

const Report = require('../../db/models/report.model');
const analysisService = require('../analysis/analysis.service');
const { generatePrefixedId } = require('../../utils/ids');
const { AppError, ERROR_CATEGORIES } = require('../../errors/errorCategories');

/**
 * Fetch a cached report or build one from a completed analysis.
 */
async function getOrCreateReport(analysisId, { language = 'en', format = 'markdown' } = {}) {
  // Cache hit - return byte-identical content.
  const cached = await Report.findOne({ analysis_id: analysisId, language, format }).lean();
  if (cached) return { report: cached, cached: true };

  const { analysis, body } = await analysisService.getFullResult(analysisId);

  // A report on an unfinished analysis would be a snapshot of incomplete
  // evidence that then gets cached forever. Refuse rather than mislead.
  if (!['completed', 'partial'].includes(analysis.status)) {
    throw new AppError(
      `Analysis ${analysisId} is not finished (status: ${analysis.status}). ` +
      'A report can only be generated once the analysis has completed.',
      ERROR_CATEGORIES.VALIDATION_FAILURE
    );
  }

  const content = buildReportContent(body, format);

  const report = await Report.create({
    report_id: generatePrefixedId('rep'),
    analysis_id: analysisId,
    format,
    content,
    language,
    // Section 67: the source of every layer/measurement must be visible as
    // evidence. Snapshotting sources keeps the report self-contained.
    sources: extractSources(body),
    summary_line: body.decision?.one_line_recommendation || null,
    generated_at: new Date(),
  });

  return { report: report.toObject(), cached: false };
}

/**
 * Build the advisory text.
 *
 * Deliberately assembled from STORED FIELDS rather than generated by an LLM at
 * read time: a report must be reproducible. The AI Service's narrative text is
 * included where it exists, but the structure and the numbers come from the
 * persisted evidence.
 */
function buildReportContent(result, format) {
  if (format === 'json') return result;

  const lines = [];

  lines.push(`# ORCA Marine Advisory`);
  lines.push('');
  lines.push(`**Analysis ID:** ${result.analysis_id}`);
  lines.push(`**Status:** ${result.status}`);

  // Location and time now come from the ExecutionPlan (contracts/
  // ExecutionPlan.json), which is what `plan` holds on the result response.
  const plan = result.plan || {};
  const location = plan.location || null;
  const timeWindow = plan.time_window || null;

  if (location?.original?.name) {
    lines.push(`**Location:** ${location.original.name}`);
  }
  if (location?.original?.lat !== undefined && location?.original?.lat !== null) {
    lines.push(`**Coordinates:** ${location.original.lat}, ${location.original.lon}`);
  }
  // Section 13.3: if the point was moved offshore, the advisory must SAY SO -
  // the user asked about one place and we analysed another.
  if (location?.validated?.snapped) {
    lines.push(
      `**Note:** The requested point was on land and was moved offshore ` +
      `(${location.validated.snap_distance_km ?? 'distance not recorded'} km)` +
      (location.validated.snap_reference ? `, ${location.validated.snap_reference}` : '') +
      '.'
    );
  }
  // TimeWindow.local is an ISO 8601 interval string "start/end".
  if (timeWindow?.local) {
    lines.push(`**Window (local):** ${timeWindow.local}`);
  }
  if (timeWindow?.original_expression) {
    lines.push(`**Requested as:** "${timeWindow.original_expression}"`);
  }
  if (plan.activity) lines.push(`**Activity:** ${plan.activity}`);
  if (plan.vessel_type) {
    lines.push(
      `**Vessel:** ${plan.vessel_type}` +
      // Section 7.7: state the assumption when a default was substituted.
      (plan.vessel_assumed ? ' _(assumed - not supplied in the request)_' : '')
    );
  }

  lines.push('');
  lines.push('## Recommendation');
  lines.push('');

  if (result.decision) {
    lines.push(`**${result.decision.one_line_recommendation || 'No summary available.'}**`);
    lines.push('');
    if (result.decision.detailed_recommendation) {
      lines.push(result.decision.detailed_recommendation);
      lines.push('');
    }
    if (result.decision.key_findings?.length) {
      lines.push('### Key findings');
      for (const finding of result.decision.key_findings) lines.push(`- ${finding}`);
      lines.push('');
    }
    if (result.decision.best_time_windows?.length) {
      lines.push('### Best time windows');
      for (const window of result.decision.best_time_windows) {
        lines.push(
          `- ${window.start_local || window.start_utc || '?'} to ` +
          `${window.end_local || window.end_utc || '?'} (${window.level || 'unrated'})` +
          (window.reason ? ` - ${window.reason}` : '')
        );
      }
      lines.push('');
    }
  } else {
    // Honest absence rather than an invented recommendation.
    lines.push('_No decision was produced for this analysis._');
    lines.push('');
  }

  // Per-point evidence table.
  if (result.points?.length) {
    lines.push('## Conditions by point');
    lines.push('');
    lines.push('| Point | Lat | Lon | Risk | Score | Status |');
    lines.push('|---|---|---|---|---|---|');
    for (const point of result.points) {
      // 'not rated' / 'n/a' are shown where risk was not computed. We do NOT
      // substitute a number, because an invented score is exactly the failure
      // mode the never-fabricate rule exists to prevent.
      lines.push(
        `| ${point.point_id} | ${point.lat} | ${point.lon} | ` +
        `${point.risk?.risk_level ?? 'not rated'} | ` +
        `${point.risk?.final_score ?? 'n/a'} | ${point.point_status ?? 'unknown'} |`
      );
    }
    lines.push('');
  }

  // Section 41 + never-fabricate: missing data is STATED, not hidden. An
  // omitted field looks like it was never needed; an explicit statement shows
  // it was needed and could not be obtained.
  const unavailable = new Set();
  for (const point of result.points || []) {
    for (const [parameter, measurement] of Object.entries(point.measurements || {})) {
      if (measurement && !['available', 'derived'].includes(measurement.status)) {
        unavailable.add(`${parameter} (${measurement.status})`);
      }
    }
  }
  if (unavailable.size) {
    lines.push('## Data limitations');
    lines.push('');
    lines.push(
      'The following parameters were unavailable and were NOT estimated: ' +
      `${[...unavailable].sort().join(', ')}.`
    );
    lines.push('');
  }

  lines.push('## Sources');
  lines.push('');
  const sources = extractSources(result);
  if (sources.length) {
    for (const source of sources) {
      lines.push(`- ${source.source}${source.retrieved_at ? ` (retrieved ${source.retrieved_at})` : ''}`);
    }
  } else {
    lines.push('_No sources recorded._');
  }
  lines.push('');
  lines.push(`_Generated by ORCA at ${new Date().toISOString()}_`);

  const markdown = lines.join('\n');
  // 'text' is the same content with markdown emphasis stripped, for SMS/voice.
  return format === 'text' ? markdown.replace(/[#*_|]/g, '') : markdown;
}

/** Collect the distinct sources behind every measurement, for the evidence panel. */
function extractSources(result) {
  // measurements is a MAP keyed by canonical parameter name
  // (contracts/Measurement.json), not an array.
  const seen = new Map();
  for (const point of result.points || []) {
    for (const measurement of Object.values(point.measurements || {})) {
      if (measurement?.source && !seen.has(measurement.source)) {
        seen.set(measurement.source, {
          source: measurement.source,
          product_id: measurement.product_id || null,
          retrieved_at: measurement.retrieved_at || null,
        });
      }
    }
  }
  return [...seen.values()];
}

module.exports = { getOrCreateReport, buildReportContent, extractSources };
